### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by PatNei** [ITU-BDSA23-GROUP9/Chirp#120]
# Process
- alle ser ud til at committe
  - lanaitu har lidt færre end jer andre, det ikke jordens undergang men det er noget helge vil kigge på når han skal rette
  - Baseret på overstående billede og hvad jeg lige kunne se ud fra jeres commit historie
- Husk at lukke jeres issues når de er done
  - Hint: Man kan få github projects til at gøre det når et issue ryger ind i done. [Eksempel](https://github.com/ITU-BDSA23-GROUP9/Chirp/issues/94)
- Jeres issues ser gode ud og følger user story / acceptance criteria kravet
  - Jeg synes dog ikke det ligner at fordelingen af hvem der laver issues er ulige. 
  - Nu bliver du lige singlet out sorry men Oline f.eks. har haft to issues fra sin profil siden sidste review synes heller ikke jeg kan se særlig mange fra lanaitu
    - Jeg kan godt se at i skriver hinanden på som co-authors som jeg anbefalede sidst
    - Men selvom i laver dem sammen bør der ligge nogen fra alle jeres accounts, så alle får skrevet nogen. 
      - Jeg ved godt det virker lidt dumt, men det er sådan Helge gerne vil have det og jeg har spurgt om det ikke gik at i bare skrev hinanden på som co-authors og han var lidt hesitant omkring det. Så vil anbefale at holde jer til at skiftes om det desværre :)
    - No worries at i ikke har nogen lige nu, bare i fremtiden så lav også nogle fra jeres account. 
- Jeg kan se jeres automation fungerer! nice
  - Angående jeres releases, så ser helge helst at man releaser flere gange om ugen men minimum 1 gang.
    - At det ikke er den bedste user experience at faktisk at bruge jeres program som en binary er underordnet bare det bliver releaset. Håber det giver mening?
- Mange små incremental steps, godt!
- Jeg kan se at i bruger code reviews til jeres pull request, hvilket er rigtig godt
  - Jeg ser dog mange lgtm's
  - Overvej om i føler at det er svært at kritisere hinandens kode eller forslå ændringer
    - Det er en del af den agile process at man bouncer sin kode frem og tilbage indtil den er helt klar til at blive merget ind i main
      - En added value er at alle får bedre ownership over koden i sin helhed
      - Man lærer gode tricks af sine kammerater
      - og/eller du kan lære dem nogle gode tricks som du kender
  - Meningen med reviews er at man kigger på kode ændringer og kommer med forbedringer, ændringer eller spørgsmål
    - HINT: Det noget helge gerne vil have og er læringsmålet med at bruge det system (:
    - Det handler selvfølgelig ikke om at finde på et eller andet trivielt problem i et gruppe medlems pull request, bare for at skabe en diskussion.
    - håber det giver mening!
    - Ekstra HINT: Kig på nogle af de andre gruppers pull request hvordan gør de det? 
    - Jeg kan nævne gruppe 10 som et eksempel hvor deres reviews er meget iterative.

#### Ellers godt arbejde med jeres process!

# Software development
![Alt text](image-1.png)
oh shit

- Jeg tænker at i har all reds pga. et eller andet med jeres azure side 
- Det ligner at i har fået pagination til at virke. 
  - Det ligner at i gør dette i client side, overvej om det ikke giver mere mening at gøre det i jeres repository, så man spare bandwith
    - Det kan også være i allerede gør dette, i det tilfælde så glem det
    - Hvis i ikke synes det giver mening at gøre det der, så skal i selvfølgelig ikke gøre det, bare så længe i overvejer hvorfor i synes det ikke giver mening.
- Ingen onion architecture endnu
  - Helt fint det er en relativ ny opgave men de er bedst hvis i får det refaktoreret til det soonish.
- Et tip er at passe på med at have klasser i klasser. Kan se at jeres Cheep og Author ligger i Model.cs. 
  - Dotnet er selvfølgelig ligeglad med hvordan i gør det 
    - Men når man skal få et overblik over jeres kode, så bliver det mega svært at finde hovede og hale i det hele.
      - En anden gruppe havde et interface erklæret i en fil og jeg troede ikke de havde et interface overhovedet
        - Så den fik de minus for indtil at vi snakkede om det i reviewet
      - Det er selvfølgelig ikke for min skyld i skal gøre det, men for helge og rasmus' som skal give jer karakter for jeres kode
  - Overvej også hvor meget cheep og author klassen egentlig har at gøre med jeres context. 
  - Ikke super meget, da context i bund og grund er ligeglad med hvad den får af input.
    - Med context mener jeg jeres Model.cs
- I bør have et repository og dto's for både author og cheeps
  - Der var nærmest  ingen af de andre grupper der havde det så no worries
  - men i bør refaktorere det i fremtiden
- I bruger inmemory database til testing. NJ!
- I mangler integration test, men kan se at i har kommenteret det ud så regner med at i er i fuldt sving
  - I bør have en der tester jeres pagination.

**Comment by AntonFriis** [comment]
WIP issue #124  and issue #125
