### ISSUE TITLE
As a Developer, I want to make an Integration test for pagination, to ensure that the program functions as intended.

### ISSUE THREAD

**Issue by olinesk** [ITU-BDSA23-GROUP9/Chirp#124]
Acceptance Criteria:

- It is tested that a page contains no more than 32 Cheeps
- It is tested that the page on "/" is on the same page as the "/?pageNumber=1"

Co-authored-by:
@AntonFriis 
@JKramer91 
@ClaraWJ 
@lanaitu 
@JohanSandager

**Comment by AntonFriis** [comment]
Works on 4/6 computers and on production
