### ISSUE TITLE
As a developer, I want to have E2E tests, so I can make sure the entire project works

### ISSUE THREAD

**Issue by JohanSandager** [ITU-BDSA23-GROUP9/Chirp#33]
Acceptance Criteria:
- E2E test for Chirp.CLI

**Comment by ClaraWJ** [comment]
Need to be worked on further, but we have chosen to postpone this to after we have implemented everything from week 5.

**Comment by lanaitu** [comment]
🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳
