### ISSUE TITLE
As a developer, I want to modify the database queries to support a fixed amount of cheeps returned.

### ISSUE THREAD

**Issue by JKramer91** [ITU-BDSA23-GROUP9/Chirp#59]
Acceptance criteria:
- The cheeps are filtered through an SQL query.
- Relevant tests are added.

Co-authored by:
@AntonFriis 
@olinesk 
@lanaitu 
@JohanSandager

**Comment by AntonFriis** [comment]
Updated acceptance criteria:
- The cheeps are filtered through an SQL query, not C#.
to
- The cheeps are filtered through an SQL query.
